//This file was generated by script mkregs.py

//register address mapping
#define KNN_RESET 0
#define KNN_ENABLE 1
#define KNN_X1 2
#define KNN_X2 3
#define KNN_Y1 4
#define KNN_Y2 5
#define KNN_VALUE_HIGH 6
#define KNN_VALUE_LOW 7
